# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='contents',
        ),
    ]
