# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contributor_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='nick_name',
            field=tinymce.models.HTMLField(default=datetime.datetime(2016, 3, 19, 4, 56, 24, 299813, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
