# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20160319_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='nick_name',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
